### ISSUE TITLE
Suit symbols don't appear correctly

### ISSUE THREAD

**Issue by anntzer** [ChristophBerg/tenace#1]
Using 0.13 on Arch Linux (`./configure --prefix=/usr LDFLAGS=-lm; make; make install`, see packaging script at https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=tenace), the suit symbols don't show up correctly:

![tenace](https://cloud.githubusercontent.com/assets/1322974/9861448/45bef820-5ae7-11e5-8f2a-c01d5a1fc169.png)

This may be a packaging issue though.

**Comment by anntzer** [comment]
Issue confirmed by building and installing the package by hand, from a git checkout.

**Comment by df7cb** [comment]
Hi,
I've seen the problem myself in the past. My guess was that it depends on the set of fonts installed, e.g. if you had MS's dingbats.ttf installed or not, but I never dug down into the details so far.
I'll see if I can find a solution. Thanks for the report!

**Comment by anntzer** [comment]
Just #defining

```
#define FONT_SYMBOL cairo_select_font_face (cr, "Sans", CAIRO_FONT_SLANT_NORMAL, CAIRO_FONT_WEIGHT_BOLD)
```

(instead of "Symbol") in `hand_display.c` (line 187) seems to solve the issue for me.

Note that http://cairographics.org/manual/cairo-text.html#cairo-select-font-face indicates that

> Cairo provides no operation to list available family names on the system (this is a "toy", remember), but the standard CSS2 generic family names, ("serif", "sans-serif", "cursive", "fantasy", "monospace"), are likely to work as expected

and that https://www.w3.org/TR/CSS2/fonts.html#generic-font-families does not list "Symbol" as a generic family name.
