### ISSUE TITLE
button hint text is barely legible

### ISSUE THREAD

**Issue by anntzer** [ChristophBerg/tenace#2]
![screenshot_20160226_113003](https://cloud.githubusercontent.com/assets/1322974/13363057/7e934928-dc7c-11e5-98da-d99673dfbb07.png)
Not-so important but a bit annoying: the button hint text is in white and barely legible (running KDE5).

**Comment by anntzer** [comment]
Was due to some theming issues between GTK and KDE.

**Comment by df7cb** [comment]
Thanks for the update, and sorry for not getting back to you on this earlier!
