### ISSUE TITLE
Update to a more recent dds?

### ISSUE THREAD

**Issue by anntzer** [ChristophBerg/tenace#3]
DDS is now at version 2.8.3 (with a few improvements since 2.1.1) and natively supports being built as a shared library.  Perhaps worth updating?  https://github.com/dds-bridge/dds/tree/develop/src/Makefiles

**Comment by df7cb** [comment]
I've been slacking with dds updates in Debian as well, will fix soonish, thanks for the poke!

**Comment by df7cb** [comment]
I finally got around to update dds (in Debian) and tenace. I removed the embedded dds copy and added a autoconf check for the library instead.

**Comment by anntzer** [comment]
This doesn't actually build cleanly on Arch: dds/dll.h is a C++ header (it uses bool) whereas tenace needs a C compiler (due to implicit conversions e.g. of void pointers).

**Comment by df7cb** [comment]
In Debian, I got it working with https://salsa.debian.org/debian/dds/blob/master/debian/patches/bool, i.e. `#include <stdbool.h>`. I'll see to get that merged upstream.
